// cgo -godefs -- -Wall -Werror -static -I/tmp/include linux/defs1_linux.go | go run mkpost.go
// Code generated by the command above; see README.md. DO NOT EDIT.

// +build ppc,linux

package runtime

const (
	O_RDONLY    = 0x0
	O_CLOEXEC   = 0x80000
	SA_RESTORER = 0x4000000
)

type Fpxreg struct{}
type Xmmreg struct{}
type Fpstate struct{}
type Fpxreg1 struct{}
type Xmmreg1 struct{}
type Fpstate1 struct{}
type Fpreg1 struct{}
type StackT struct {
	Sp    *byte
	Flags int32
	Size  uint32
}

type Sigcontext struct{}
