// cgo -godefs -- -Wall -Werror -static -I/tmp/include linux/defs_linux.go | go run mkpost.go
// Code generated by the command above; see README.md. DO NOT EDIT.

// +build ppc,linux

package runtime

const (
	EINTR  = 0x4
	EAGAIN = 0xb
	ENOMEM = 0xc

	PROT_NONE  = 0x0
	PROT_READ  = 0x1
	PROT_WRITE = 0x2
	PROT_EXEC  = 0x4

	MAP_ANON    = 0x20
	MAP_PRIVATE = 0x2
	MAP_FIXED   = 0x10

	MADV_DONTNEED = 0x4

	SA_RESTART = 0x10000000
	SA_ONSTACK = 0x8000000
	SA_SIGINFO = 0x4

	SIGHUP    = 0x1
	SIGINT    = 0x2
	SIGQUIT   = 0x3
	SIGILL    = 0x4
	SIGTRAP   = 0x5
	SIGABRT   = 0x6
	SIGBUS    = 0x7
	SIGFPE    = 0x8
	SIGKILL   = 0x9
	SIGUSR1   = 0xa
	SIGSEGV   = 0xb
	SIGUSR2   = 0xc
	SIGPIPE   = 0xd
	SIGALRM   = 0xe
	SIGSTKFLT = 0x10
	SIGCHLD   = 0x11
	SIGCONT   = 0x12
	SIGSTOP   = 0x13
	SIGTSTP   = 0x14
	SIGTTIN   = 0x15
	SIGTTOU   = 0x16
	SIGURG    = 0x17
	SIGXCPU   = 0x18
	SIGXFSZ   = 0x19
	SIGVTALRM = 0x1a
	SIGPROF   = 0x1b
	SIGWINCH  = 0x1c
	SIGIO     = 0x1d
	SIGPWR    = 0x1e
	SIGSYS    = 0x1f

	FPE_INTDIV = 0x1
	FPE_INTOVF = 0x2
	FPE_FLTDIV = 0x3
	FPE_FLTOVF = 0x4
	FPE_FLTUND = 0x5
	FPE_FLTRES = 0x6
	FPE_FLTINV = 0x7
	FPE_FLTSUB = 0x8

	BUS_ADRALN = 0x1
	BUS_ADRERR = 0x2
	BUS_OBJERR = 0x3

	SEGV_MAPERR = 0x1
	SEGV_ACCERR = 0x2

	ITIMER_REAL    = 0x0
	ITIMER_VIRTUAL = 0x1
	ITIMER_PROF    = 0x2

	EPOLLIN       = 0x1
	EPOLLOUT      = 0x4
	EPOLLERR      = 0x8
	EPOLLHUP      = 0x10
	EPOLLRDHUP    = 0x2000
	EPOLLET       = 0x80000000
	EPOLL_CLOEXEC = 0x80000
	EPOLL_CTL_ADD = 0x1
	EPOLL_CTL_DEL = 0x2
	EPOLL_CTL_MOD = 0x3
)

type Sigset struct {
	Sig [2]uint32
}
type Timespec struct {
	Sec  int32
	Nsec int32
}
type Timeval struct {
	Sec  int32
	Usec int32
}
type Sigaction struct {
	Handler  *[0]byte
	Flags    uint32
	Restorer *[0]byte
	Mask     Sigset
}
type Siginfo struct {
	Anon0 [128]byte
}
type Itimerval struct {
	Interval Timeval
	Value    Timeval
}
type EpollEvent struct {
	Events uint32
	_      [4]byte
	Data   uint64
}
